### ISSUE TITLE
PowerPC builds

### ISSUE THREAD

**Issue by jaimergp** [conda-forge/nvcc-feedstock#21]
It would be nice to add support for `ppc64le` architectures. I don't know if the current system would work OK for this situation, since it assumes one CUDA version = one Docker image.

Even if that gets solved, there are some external barriers:

* [Nvidia has Docker images](https://hub.docker.com/r/nvidia/cuda-ppc64le/), but no CentOS 6; only CentOS 7 and Ubuntu 16/18. I read at some point that `conda-forge` would eventually migrate to CentOS 7, but I have no idea when that's going to happen.
* [Anaconda has `cudatoolkit` for `ppc64le`](https://anaconda.org/anaconda/cudatoolkit), but only for `v9.0`.

I'll leave this here for future reference and update as needed. Thanks!

**Comment by jakirkham** [comment]
Yep, I think you have more-or-less outlined the issues that have been in our heads. Thanks for doing that. 🙂

We've requested CentOS 6 ppc64le images in [this upstream issue]( https://gitlab.com/nvidia/container-images/cuda-ppc64le/issues/7 ). This may happen as part of making multiarch Docker images tracked in [this upstream issue]( https://gitlab.com/nvidia/container-images/cuda/issues/41 ).

That said, [our ppc64le stack uses CentOS 7]( https://github.com/conda-forge/docker-images/blob/d457a357bbdd9814a656e90599529f70ae6d5b6f/linux-anvil-ppc64le/Dockerfile#L1 ) anyways. This due to the fact that there are [only CentOS 7 ppc64le base images]( https://hub.docker.com/r/ppc64le/centos ). So using CentOS 7 for ppc64le GPU builds would be fine and is already compatible with how we build things on that architecture.

We did start working on CentOS 7-based NVIDIA-derived ppc64le images in PR ( https://github.com/conda-forge/docker-images/pull/113 ). However this ran into issues due to the lack of more recent `cudatoolkit` versions (as you have noted). Currently [`defaults` does not plan to update `cudatoolkit` for ppc64le]( https://github.com/conda-forge/docker-images/pull/113#issuecomment-530455729 ). So things have stopped there. It would be good to unblock this somehow though.

**Comment by isuruf** [comment]
Why can't we distribute the cudatoolkit? Debian ships the libraries and the compiler. (Maybe with NVIDIA permission?)

**Comment by kkraus14** [comment]
We're investigating this internally to see if there's any licensing / legal issues and will report back.

**Comment by jaimergp** [comment]
Thanks for the detailed update, @jakirkham! I'll keep an eye on this.

**Comment by jayfurmanek** [comment]
There was no ppc64le version of CENTOS6. It predates ppc64le being an official Linux arch so we'd have to start with CENTOS7 for ppc64le.

I agree, it would be great if forge could distribute the cuda toolkit!

**Comment by leofang** [comment]
> We're investigating this internally to see if there's any licensing / legal issues and will report back.

@kkraus14 Any update for this inquiry? Thanks!
