### ISSUE TITLE
[BUG] Redefinition of '-ccbin' argument

### ISSUE THREAD

**Issue by teju85** [conda-forge/nvcc-feedstock#34]
Issue:
If the project build system explicitly tries to customize compiler path by passing `-ccbin` option, then this package ends up with the following error:
`nvcc fatal   : redefinition of argument 'compiler-bindir'`
This seems to happen because the nvcc wrapper script explicitly tries to pass `-ccbin` itself.
<br/>

Environment (<code>conda list</code>):
[conda-list.txt](https://github.com/conda-forge/nvcc-feedstock/files/3982456/conda-list.txt)
<br/>

Details about  <code>conda</code> and system ( <code>conda info</code> ):
[conda-info.txt](https://github.com/conda-forge/nvcc-feedstock/files/3982465/conda-info.txt)

Additional information:
To know more about why we pass `-ccbin` option ourselves, refer to our [cuML CMakeLists.txt](https://github.com/rapidsai/cuml/blob/branch-0.12/cpp/CMakeLists.txt#L172)

**Comment by carterbox** [comment]
I have this same issue, but in my `CMakeLists.txt` I define
```cmake
set(CMAKE_CUDA_HOST_COMPILER ${CMAKE_CXX_COMPILER})
```
Otherwise, `nvcc` doesn't always choose the whatever compiler is set using the environment variable `CXX` as the host compiler. I guess this is the same reason that the nvcc wrapper uses the `-ccbin` parameter.

As a work-around, instead of the above CMAKE call, I can also set the environment variable `CUDAHOSTCXX` whenever I'm not using `conda-forge nvcc`.
